# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'biota.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MyPluginDialogBase(object):
    def setupUi(self, MyPluginDialogBase):
        MyPluginDialogBase.setObjectName("MyPluginDialogBase")
        MyPluginDialogBase.setEnabled(True)
        MyPluginDialogBase.resize(851, 846)
        self.button_box = QtWidgets.QDialogButtonBox(MyPluginDialogBase)
        self.button_box.setGeometry(QtCore.QRect(490, 810, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.groupBox = QtWidgets.QGroupBox(MyPluginDialogBase)
        self.groupBox.setGeometry(QtCore.QRect(20, 260, 401, 431))
        self.groupBox.setObjectName("groupBox")
        self.checkBox_FCH = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_FCH.setGeometry(QtCore.QRect(230, 360, 201, 22))
        self.checkBox_FCH.setObjectName("checkBox_FCH")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 81, 31))
        self.label_2.setObjectName("label_2")
        self.lineEdit_Lat = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Lat.setGeometry(QtCore.QRect(10, 120, 81, 27))
        self.lineEdit_Lat.setObjectName("lineEdit_Lat")
        self.checkBox_Go = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_Go.setGeometry(QtCore.QRect(40, 320, 91, 22))
        self.checkBox_Go.setObjectName("checkBox_Go")
        self.lineEdit_Lon = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Lon.setEnabled(True)
        self.lineEdit_Lon.setGeometry(QtCore.QRect(120, 120, 81, 27))
        self.lineEdit_Lon.setObjectName("lineEdit_Lon")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(120, 90, 81, 31))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 161, 31))
        self.label.setObjectName("label")
        self.checkBox_chg = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_chg.setGeometry(QtCore.QRect(200, 210, 141, 22))
        self.checkBox_chg.setObjectName("checkBox_chg")
        self.checkBox_AGB = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_AGB.setGeometry(QtCore.QRect(40, 360, 201, 22))
        self.checkBox_AGB.setChecked(True)
        self.checkBox_AGB.setObjectName("checkBox_AGB")
        self.pushButton_INP = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_INP.setGeometry(QtCore.QRect(320, 50, 51, 27))
        self.pushButton_INP.setObjectName("pushButton_INP")
        self.lineEdit_Y1 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Y1.setGeometry(QtCore.QRect(10, 270, 91, 27))
        self.lineEdit_Y1.setObjectName("lineEdit_Y1")
        self.lineEdit_Y2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Y2.setGeometry(QtCore.QRect(200, 270, 91, 27))
        self.lineEdit_Y2.setFrame(True)
        self.lineEdit_Y2.setDragEnabled(False)
        self.lineEdit_Y2.setObjectName("lineEdit_Y2")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 240, 81, 31))
        self.label_4.setObjectName("label_4")
        self.checkBox_BCH = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_BCH.setGeometry(QtCore.QRect(230, 320, 201, 22))
        self.checkBox_BCH.setObjectName("checkBox_BCH")
        self.lineEdit_INP = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_INP.setGeometry(QtCore.QRect(10, 50, 301, 27))
        self.lineEdit_INP.setObjectName("lineEdit_INP")
        self.checkBox_pty = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_pty.setGeometry(QtCore.QRect(10, 210, 141, 22))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_pty.setFont(font)
        self.checkBox_pty.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.checkBox_pty.setAutoFillBackground(False)
        self.checkBox_pty.setChecked(True)
        self.checkBox_pty.setObjectName("checkBox_pty")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(200, 240, 81, 31))
        self.label_5.setObjectName("label_5")
        self.checkBox_WCV = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_WCV.setGeometry(QtCore.QRect(40, 400, 201, 22))
        self.checkBox_WCV.setObjectName("checkBox_WCV")
        self.checkBox_RSK = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_RSK.setGeometry(QtCore.QRect(230, 400, 201, 22))
        self.checkBox_RSK.setObjectName("checkBox_RSK")
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider.setGeometry(QtCore.QRect(260, 140, 81, 21))
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(5)
        self.horizontalSlider.setSingleStep(4)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(260, 110, 91, 31))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(240, 150, 31, 31))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(340, 150, 31, 31))
        self.label_16.setObjectName("label_16")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 160, 211, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.helpButton_lat = QtWidgets.QPushButton(self.groupBox)
        self.helpButton_lat.setGeometry(QtCore.QRect(90, 120, 21, 21))
        self.helpButton_lat.setObjectName("helpButton_lat")
        self.helpButton_lon = QtWidgets.QPushButton(self.groupBox)
        self.helpButton_lon.setGeometry(QtCore.QRect(200, 120, 21, 20))
        self.helpButton_lon.setObjectName("helpButton_lon")
        self.helpButton_fch = QtWidgets.QPushButton(self.groupBox)
        self.helpButton_fch.setGeometry(QtCore.QRect(200, 360, 21, 20))
        self.helpButton_fch.setObjectName("helpButton_fch")
        self.helpButton_bch = QtWidgets.QPushButton(self.groupBox)
        self.helpButton_bch.setGeometry(QtCore.QRect(200, 320, 21, 20))
        self.helpButton_bch.setObjectName("helpButton_bch")
        self.helpButton_rsk = QtWidgets.QPushButton(self.groupBox)
        self.helpButton_rsk.setGeometry(QtCore.QRect(200, 400, 21, 20))
        self.helpButton_rsk.setObjectName("helpButton_rsk")
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(160, 240, 20, 181))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.helpButton_bio = QtWidgets.QPushButton(self.groupBox)
        self.helpButton_bio.setGeometry(QtCore.QRect(10, 360, 21, 20))
        self.helpButton_bio.setObjectName("helpButton_bio")
        self.helpButton_g0 = QtWidgets.QPushButton(self.groupBox)
        self.helpButton_g0.setGeometry(QtCore.QRect(10, 320, 21, 20))
        self.helpButton_g0.setObjectName("helpButton_g0")
        self.helpButton_for = QtWidgets.QPushButton(self.groupBox)
        self.helpButton_for.setGeometry(QtCore.QRect(10, 400, 21, 20))
        self.helpButton_for.setObjectName("helpButton_for")
        self.groupBox_2 = QtWidgets.QGroupBox(MyPluginDialogBase)
        self.groupBox_2.setGeometry(QtCore.QRect(440, 260, 391, 381))
        self.groupBox_2.setObjectName("groupBox_2")
        self.checkBox_FIL = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_FIL.setGeometry(QtCore.QRect(40, 120, 201, 22))
        self.checkBox_FIL.setChecked(True)
        self.checkBox_FIL.setObjectName("checkBox_FIL")
        self.spinBox_SUB = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_SUB.setGeometry(QtCore.QRect(250, 115, 60, 27))
        self.spinBox_SUB.setWrapping(False)
        self.spinBox_SUB.setMinimum(1)
        self.spinBox_SUB.setProperty("value", 1)
        self.spinBox_SUB.setObjectName("spinBox_SUB")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(250, 95, 131, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 160, 201, 31))
        self.label_8.setObjectName("label_8")
        self.lineEdit_POL = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_POL.setGeometry(QtCore.QRect(10, 190, 91, 27))
        self.lineEdit_POL.setObjectName("lineEdit_POL")
        self.lineEdit_ATH = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_ATH.setGeometry(QtCore.QRect(10, 260, 91, 27))
        self.lineEdit_ATH.setObjectName("lineEdit_ATH")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(10, 230, 131, 31))
        self.label_9.setObjectName("label_9")
        self.lineEdit_BTH = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_BTH.setGeometry(QtCore.QRect(10, 330, 91, 27))
        self.lineEdit_BTH.setObjectName("lineEdit_BTH")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(10, 300, 181, 31))
        self.label_10.setObjectName("label_10")
        self.lineEdit_ACH = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_ACH.setGeometry(QtCore.QRect(220, 190, 91, 27))
        self.lineEdit_ACH.setObjectName("lineEdit_ACH")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(220, 160, 121, 31))
        self.label_11.setObjectName("label_11")
        self.lineEdit_BCH = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_BCH.setGeometry(QtCore.QRect(220, 260, 91, 27))
        self.lineEdit_BCH.setObjectName("lineEdit_BCH")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(220, 230, 161, 31))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(220, 300, 141, 31))
        self.label_18.setObjectName("label_18")
        self.lineEdit_PCH = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_PCH.setGeometry(QtCore.QRect(220, 330, 91, 27))
        self.lineEdit_PCH.setObjectName("lineEdit_PCH")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 161, 31))
        self.label_6.setObjectName("label_6")
        self.lineEdit_OUT = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_OUT.setGeometry(QtCore.QRect(10, 50, 301, 27))
        self.lineEdit_OUT.setObjectName("lineEdit_OUT")
        self.pushButton_OUT = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_OUT.setGeometry(QtCore.QRect(320, 50, 51, 27))
        self.pushButton_OUT.setObjectName("pushButton_OUT")
        self.helpButton_pol = QtWidgets.QPushButton(self.groupBox_2)
        self.helpButton_pol.setGeometry(QtCore.QRect(100, 190, 21, 20))
        self.helpButton_pol.setObjectName("helpButton_pol")
        self.helpButton_ach = QtWidgets.QPushButton(self.groupBox_2)
        self.helpButton_ach.setGeometry(QtCore.QRect(310, 190, 21, 20))
        self.helpButton_ach.setObjectName("helpButton_ach")
        self.helpButton_ath = QtWidgets.QPushButton(self.groupBox_2)
        self.helpButton_ath.setGeometry(QtCore.QRect(100, 260, 21, 20))
        self.helpButton_ath.setObjectName("helpButton_ath")
        self.helpButton_bth = QtWidgets.QPushButton(self.groupBox_2)
        self.helpButton_bth.setGeometry(QtCore.QRect(100, 330, 21, 20))
        self.helpButton_bth.setObjectName("helpButton_bth")
        self.helpButton_BCH = QtWidgets.QPushButton(self.groupBox_2)
        self.helpButton_BCH.setGeometry(QtCore.QRect(310, 260, 21, 20))
        self.helpButton_BCH.setObjectName("helpButton_BCH")
        self.helpButton_pch = QtWidgets.QPushButton(self.groupBox_2)
        self.helpButton_pch.setGeometry(QtCore.QRect(310, 330, 21, 20))
        self.helpButton_pch.setObjectName("helpButton_pch")
        self.helpButton_fil = QtWidgets.QPushButton(self.groupBox_2)
        self.helpButton_fil.setGeometry(QtCore.QRect(10, 120, 21, 20))
        self.helpButton_fil.setObjectName("helpButton_fil")
        self.helpButton_sub = QtWidgets.QPushButton(self.groupBox_2)
        self.helpButton_sub.setGeometry(QtCore.QRect(220, 120, 21, 20))
        self.helpButton_sub.setObjectName("helpButton_sub")
        self.progressBar_PRC = QtWidgets.QProgressBar(MyPluginDialogBase)
        self.progressBar_PRC.setGeometry(QtCore.QRect(20, 770, 401, 23))
        self.progressBar_PRC.setProperty("value", 0)
        self.progressBar_PRC.setObjectName("progressBar_PRC")
        self.label_12 = QtWidgets.QLabel(MyPluginDialogBase)
        self.label_12.setGeometry(QtCore.QRect(20, 750, 251, 17))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(MyPluginDialogBase)
        self.label_13.setGeometry(QtCore.QRect(20, 700, 121, 17))
        self.label_13.setObjectName("label_13")
        self.progressBar_DLD = QtWidgets.QProgressBar(MyPluginDialogBase)
        self.progressBar_DLD.setGeometry(QtCore.QRect(20, 720, 401, 23))
        self.progressBar_DLD.setProperty("value", 0)
        self.progressBar_DLD.setObjectName("progressBar_DLD")
        self.label_19 = QtWidgets.QLabel(MyPluginDialogBase)
        self.label_19.setGeometry(QtCore.QRect(20, 10, 361, 61))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_21 = QtWidgets.QLabel(MyPluginDialogBase)
        self.label_21.setGeometry(QtCore.QRect(470, 10, 321, 241))
        self.label_21.setObjectName("label_21")
        self.groupBox_3 = QtWidgets.QGroupBox(MyPluginDialogBase)
        self.groupBox_3.setGeometry(QtCore.QRect(440, 650, 391, 141))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        self.label_22.setGeometry(QtCore.QRect(10, 30, 371, 101))
        self.label_22.setObjectName("label_22")
        self.helpButton = QtWidgets.QPushButton(MyPluginDialogBase)
        self.helpButton.setGeometry(QtCore.QRect(20, 810, 101, 25))
        self.helpButton.setObjectName("helpButton")
        self.label_23 = QtWidgets.QLabel(MyPluginDialogBase)
        self.label_23.setGeometry(QtCore.QRect(20, 76, 381, 171))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(MyPluginDialogBase)
        self.label_24.setGeometry(QtCore.QRect(620, 40, 91, 51))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(MyPluginDialogBase)
        self.label_25.setGeometry(QtCore.QRect(789, 10, 41, 241))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(MyPluginDialogBase)
        self.label_26.setGeometry(QtCore.QRect(440, 10, 41, 241))
        self.label_26.setObjectName("label_26")
        self.label_28 = QtWidgets.QLabel(MyPluginDialogBase)
        self.label_28.setGeometry(QtCore.QRect(720, 40, 51, 51))
        self.label_28.setObjectName("label_28")

        self.retranslateUi(MyPluginDialogBase)
        self.button_box.accepted.connect(MyPluginDialogBase.accept)
        self.button_box.rejected.connect(MyPluginDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(MyPluginDialogBase)

    def retranslateUi(self, MyPluginDialogBase):
        _translate = QtCore.QCoreApplication.translate
        MyPluginDialogBase.setWindowTitle(_translate("MyPluginDialogBase", "Biota Graphical Interface"))
        self.groupBox.setTitle(_translate("MyPluginDialogBase", "Primary inputs"))
        self.checkBox_FCH.setText(_translate("MyPluginDialogBase", "Forest Cover Change"))
        self.label_2.setText(_translate("MyPluginDialogBase", "Latitude"))
        self.checkBox_Go.setText(_translate("MyPluginDialogBase", "Gamma0"))
        self.label_3.setText(_translate("MyPluginDialogBase", "Longitude"))
        self.label.setText(_translate("MyPluginDialogBase", "Input data directory"))
        self.checkBox_chg.setText(_translate("MyPluginDialogBase", "Forest change"))
        self.checkBox_AGB.setText(_translate("MyPluginDialogBase", "Biomass"))
        self.pushButton_INP.setText(_translate("MyPluginDialogBase", "..."))
        self.label_4.setText(_translate("MyPluginDialogBase", "Year 1"))
        self.checkBox_BCH.setText(_translate("MyPluginDialogBase", "Biomass Change"))
        self.checkBox_pty.setText(_translate("MyPluginDialogBase", "Forest property"))
        self.label_5.setText(_translate("MyPluginDialogBase", "Year 2"))
        self.checkBox_WCV.setText(_translate("MyPluginDialogBase", "Forest Cover"))
        self.checkBox_RSK.setText(_translate("MyPluginDialogBase", "Deforestation Risk"))
        self.label_14.setText(_translate("MyPluginDialogBase", "Tile size (km)"))
        self.label_15.setText(_translate("MyPluginDialogBase", "1x1"))
        self.label_16.setText(_translate("MyPluginDialogBase", "5x5"))
        self.pushButton_3.setText(_translate("MyPluginDialogBase", "Check on map"))
        self.helpButton_lat.setText(_translate("MyPluginDialogBase", "?"))
        self.helpButton_lon.setText(_translate("MyPluginDialogBase", "?"))
        self.helpButton_fch.setText(_translate("MyPluginDialogBase", "?"))
        self.helpButton_bch.setText(_translate("MyPluginDialogBase", "?"))
        self.helpButton_rsk.setText(_translate("MyPluginDialogBase", "?"))
        self.helpButton_bio.setText(_translate("MyPluginDialogBase", "?"))
        self.helpButton_g0.setText(_translate("MyPluginDialogBase", "?"))
        self.helpButton_for.setText(_translate("MyPluginDialogBase", "?"))
        self.groupBox_2.setTitle(_translate("MyPluginDialogBase", "Secondary inputs"))
        self.checkBox_FIL.setText(_translate("MyPluginDialogBase", "Activate speckle filter"))
        self.label_7.setText(_translate("MyPluginDialogBase", "Resample factor"))
        self.label_8.setText(_translate("MyPluginDialogBase", "Polarisation (HV, HH, VV, VH)"))
        self.lineEdit_POL.setText(_translate("MyPluginDialogBase", "HV"))
        self.lineEdit_ATH.setText(_translate("MyPluginDialogBase", "1"))
        self.label_9.setText(_translate("MyPluginDialogBase", "Area threshold (ha)"))
        self.lineEdit_BTH.setText(_translate("MyPluginDialogBase", "10"))
        self.label_10.setText(_translate("MyPluginDialogBase", "Biomass threshold (tC/ha)"))
        self.lineEdit_ACH.setText(_translate("MyPluginDialogBase", "0"))
        self.label_11.setText(_translate("MyPluginDialogBase", "Area change (ha)"))
        self.lineEdit_BCH.setText(_translate("MyPluginDialogBase", "0"))
        self.label_17.setText(_translate("MyPluginDialogBase", "Biomass change (tC/ha)"))
        self.label_18.setText(_translate("MyPluginDialogBase", "Percentage change"))
        self.lineEdit_PCH.setText(_translate("MyPluginDialogBase", "0"))
        self.label_6.setText(_translate("MyPluginDialogBase", "Output data directory"))
        self.pushButton_OUT.setText(_translate("MyPluginDialogBase", "..."))
        self.helpButton_pol.setText(_translate("MyPluginDialogBase", "?"))
        self.helpButton_ach.setText(_translate("MyPluginDialogBase", "?"))
        self.helpButton_ath.setText(_translate("MyPluginDialogBase", "?"))
        self.helpButton_bth.setText(_translate("MyPluginDialogBase", "?"))
        self.helpButton_BCH.setText(_translate("MyPluginDialogBase", "?"))
        self.helpButton_pch.setText(_translate("MyPluginDialogBase", "?"))
        self.helpButton_fil.setText(_translate("MyPluginDialogBase", "?"))
        self.helpButton_sub.setText(_translate("MyPluginDialogBase", "?"))
        self.label_12.setText(_translate("MyPluginDialogBase", "Processing data"))
        self.label_13.setText(_translate("MyPluginDialogBase", "Dowloading data"))
        self.label_19.setText(_translate("MyPluginDialogBase", "WELCOME TO BIOTA!"))
        self.label_21.setText(_translate("MyPluginDialogBase", "SMFM logo"))
        self.groupBox_3.setTitle(_translate("MyPluginDialogBase", "Help"))
        self.label_22.setText(_translate("MyPluginDialogBase", "Click on the help buttons to get parameter definitions"))
        self.helpButton.setText(_translate("MyPluginDialogBase", "Biota manual"))
        self.label_23.setText(_translate("MyPluginDialogBase", "the BIOmass Tool for Alos (BIOTA) was developped by LTS International and the University of Edinburgh. Use it to calculate above-ground biomass from L-band satellite data in dry forests and savannahs, as well as biomass change and forest degradation."))
        self.label_24.setText(_translate("MyPluginDialogBase", "LTS LOGO"))
        self.label_25.setText(_translate("MyPluginDialogBase", "white"))
        self.label_26.setText(_translate("MyPluginDialogBase", "white"))
        self.label_28.setText(_translate("MyPluginDialogBase", "uOe LOGO"))


